### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by asmethegoat** [SparklyCatTF2/il2cpp-cpp-class-generator#1]
Hello!

I need to get into contact with you about a clothing uploader bot.

I can pay 10,000 robux if you can help.

My discord user; Asme#9999

(Im sorry for submitting a issue I don't know how or where to contact you. I made my github account today just to get in touch)

**Comment by madiskoivopuu** [comment]
Hi, I've stopped making anything Roblox related completely so I can't help with a clothing upload bot. Last time I worked on Vortex was two years ago and a lot has probably changed over that time.
